//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controlpermiso
    {
        public int ControlpermisoId { get; set; }
        public bool estado_control { get; set; }
        public Nullable<int> RolId { get; set; }
        public Nullable<int> PermisoId { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Permiso Permiso { get; set; }
    }
}
