//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datopinturabarniz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Datopinturabarniz()
        {
            this.Detalle = new HashSet<Detalle>();
        }
    
        public int DatopinturabarnizId { get; set; }
        public string color { get; set; }
        public int año_duracion { get; set; }
        public double extension_area { get; set; }
        public string presentacion_pinturabarniz { get; set; }
        public string base_pinturabarniza { get; set; }
        public int producto_existencia { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public decimal precio_venta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalle { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
