//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int DetalleId { get; set; }
        public int cantidad_venta { get; set; }
        public decimal total_venta { get; set; }
        public Nullable<int> FacturaId { get; set; }
        public Nullable<int> AccesorioId { get; set; }
        public Nullable<int> SolventeId { get; set; }
        public Nullable<int> DatopinturabarnizId { get; set; }
    
        public virtual Accesorio Accesorio { get; set; }
        public virtual Datopinturabarniz Datopinturabarniz { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Solvente Solvente { get; set; }
    }
}
