//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioId { get; set; }
        public string nombre_usuario { get; set; }
        public string pass_usuario { get; set; }
        public bool estado_usuario { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public Nullable<int> RolId { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
